INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')