INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (2,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (3,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (4,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (5,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (6,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (7,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (8,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) VALUES (9,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08','');
