INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (1,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (2,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (3,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (4,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (5,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (6,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (7,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (8,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (9,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (10,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (11,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (12,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (13,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (14,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (15,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (16,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (17,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (18,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (19,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (20,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (21,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (22,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (23,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (24,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (25,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (26,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (27,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (28,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (29,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (30,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (31,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (32,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (33,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (34,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (35,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (36,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (37,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (38,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (39,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (40,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (41,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (42,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (43,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (44,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (45,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (46,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (47,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (48,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (49,'VICTOR','SOTO','UNDACVASG@HOTMAIL.COM','2017-03-08');7
INSERT INTO clientes (id,nombre,apellido,email,create_at) VALUES (50,'alberto','gutierrez','undacvasg@gmail.com','2017-03-08')
